name: Continuous Integration

on:
  workflow_dispatch:
  push:

jobs:

  main_stable:
    name: Rust stable
    uses: ./.github/workflows/_build.yml
    with:
      rust_toolchain: stable
      with_rustfmt: true
      with_clippy: true

